version: "3.4"

services:
  php:
    restart: unless-stopped
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./api:/srv/app:rw,cached
      - ./.composer:/srv/.composer:rw
      - ./.docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Mac you can remove the var/ directory from the bind-mount
      # for better performance by enabling the next line 
      - /srv/app/var
    environment:
      APP_ENV: dev

  caddy:
    restart: unless-stopped
    volumes:
      - ./.docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/public:/srv/app/public:ro
