version: "3.4"

services:

  # skilleos-api
  php:
    container_name: php
    build:
      context: .
      target: symfony_php
      args:
        APP_DIRECTORY: ./api
        SYMFONY_VERSION: 4.4.49
        PHP_VERSION: 7.4.33
        SKELETON: ${SKELETON:-symfony/skeleton}
        STABILITY: ${STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  caddy:
    build:
      context: .
      target: symfony_caddy
      args:
        APP_DIRECTORY: ./api
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-symfony}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  # Queue service
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_ERLANG_COOKIE: rabbitCookieChangeThisInProduction
    volumes:
      - "rabbitmq:/etc/rabbitmq/:ro"
      - "rabbitmq_data:/var/lib/rabbitmq/:rw"
      - "rabbitmq_logs:/var/log/rabbitmq/:rw"



volumes:
  php_socket:
  caddy_data:
  caddy_config:
  database_data:
  rabbitmq:
  rabbitmq_data:
  rabbitmq_logs:
  php_socket_worker:
  caddy_data_worker:
  caddy_config_worker: