# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        s3.storage:
            adapter: 'asyncaws'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: 'AsyncAws\S3\S3Client'
                bucket: '%s3_bucket_name%'
                prefix: '%stats_export_prefix%/'
        s3.media.storage:
            adapter: 'aws'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: 'aws_client_service' # The service ID of the Aws\S3\S3Client instance
                bucket: '%s3_bucket_name%'
                prefix: 'optional/path/prefix'
                streamReads: true